export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL";
export const CLEAR_ERRORS="CLEAR_ERRORS"

export const PRODUCTDETAILS_REQUEST="PRODUCTDETAIL_REQUEST";
export const PRODUCTDETAILS_SUCCESS="PRODUCTDETAILS_SUCCESS";
export const PRODUCTDETAILS_FAIL="PRODUCT_FAIL";
export const CLEAR_ERROR="CLEAR_ERROR";
